### ISSUE TITLE
View Match List

### ISSUE THREAD

**Issue by NathanM117** [CodePath-iOS-PlayDate/PlayDate#4]
As a user, I would like to see a list of previous pet matches.

**Comment by dabaquita** [comment]
![Screen Shot 2021-11-15 at 9 29 07 PM](https://user-images.githubusercontent.com/28579460/141884835-62142911-5d81-479c-a3f9-4d29deb07169.png)

First skeleton of what it should look like. Should be a table view with custom table view cells
